---
- name: Download Grafana APT key
  get_url:
    url: "{{ grafana_apt_key }}"
    dest: "{{ grafana_apt_keypath }}"
    mode: "0644"
    force: true
  changed_when: false

- name: Add Grafana APT repository
  apt_repository:
    repo: "{{ grafana_apt_repo_url }}"
    state: present
    update_cache: true

- name: Update APT package index
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install Grafana
  apt:
    name: grafana
    state: latest
  become: true

- name: Ensure Grafana configuration directory exists
  file:
    path: /etc/grafana
    state: directory
    owner: grafana
    group: grafana
    mode: "0755"
  become: true

- name: Deploy grafana.ini config file
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: grafana
    group: grafana
    mode: "0644"
  become: true
  notify: Restart Grafana

- name: Ensure Grafana is running
  service:
    name: grafana-server
    state: started
    enabled: yes
  become: true

- name: Ensure Grafana dashboards directory exists
  file:
    path: /etc/grafana/provisioning/dashboards
    state: directory
    owner: grafana
    group: grafana
    mode: "0755"
  become: true

- name: Ensure Grafana dashboards directory exists
  file:
    path: "{{ grafana_dashboard_path }}"
    state: directory
    owner: grafana
    group: grafana
    mode: "0755"
  become: true

- name: Ensure Grafana datasources directory exists
  file:
    path: /etc/grafana/provisioning/datasources/
    state: directory
    owner: grafana
    group: grafana
    mode: "0755"
  become: true

- name: Deploy Grafana datasource configuration
  template:
    src: grafana-datasource.yaml.j2
    dest: /etc/grafana/provisioning/datasources/datasource.yaml
    owner: grafana
    group: grafana
    mode: "0755"
  become: true
  notify: Restart Grafana

- name: Deploy Grafana dashboard configuration
  template:
    src: grafana-dashboard.yaml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboard.yaml
    owner: grafana
    group: grafana
    mode: "0755"
  become: true
  notify: Restart Grafana

- name: Deploy Prometheus default dashboard
  copy:
    src: "{{ grafana_example_dashboard_host_path }}"
    dest: "{{ grafana_example_dashboard_path }}"
    owner: grafana
    group: grafana
    mode: "0755"
  become: true
  notify: Restart Grafana
