#SPDX-License-Identifier: MIT-0
### REQUIRED
# The namespace of the collection. This can be a company/brand/organization or product namespace under which all
# content lives. May only contain alphanumeric lowercase characters and underscores. Namespaces cannot start with
# underscores or numbers and cannot contain consecutive underscores
namespace: iac

# The name of the collection. Has the same character restrictions as 'namespace'
name: lab4
version: 1.0.0
readme: README.md
authors:
  - Svyatoslav
description: your collection description
license:
  - GPL-2.0-or-later
license_file: ""
tags: []
dependencies: {}
# The URL of the originating SCM repository
repository: https://github.com/krsvt/iac4
# The URL to any online docs
documentation: https://github.com/krsvt/iac4
# The URL to the homepage of the collection/project
homepage: https://github.com/krsvt/iac4
# The URL to the collection issue tracker
issues: https://github.com/krsvt/iac4
build_ignore: []
