---
grafana_apt_key: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xb53ae77badb630a683046005963fa27710458545
grafana_apt_keypath: /usr/share/keyrings/grafana.asc
grafana_repo_url: https://mirror.yandex.ru/mirrors/packages.grafana.com/oss/deb
grafana_apt_repo_url: "deb [signed-by={{ grafana_apt_keypath }}] {{ grafana_repo_url }} stable main"

# ini file
grafana_http_port: 3000
grafana_root_url: http://localhost:3000
grafana_disable_sign_up: true
grafana_auth_anonymous: false
grafana_admin_user: admin
grafana_admin_password: admin

# grafana-dashboard.yaml
grafana_dashboard_provider_name: Default Dashboard Provider
grafana_dashboard_update_interval: 30
grafana_dashboard_path: /var/lib/grafana/dashboards

# grafana-datasource.yaml
grafana_prometheus_url: http://localhost:9090
grafana_loki_url: http://localhost:3100

grafana_example_dashboard_host_path: files/grafana/provisioning/dashboards/example-service-dashboard.json
grafana_example_dashboard_path: "{{grafana_dashboard_path}}/example-service-dashboard.json"
